import { Amaranth } from "next/font/google";

import "./globals.css";
import Header from "./_component/Header";
import { Fuzzy_Bubbles } from "next/font/google";
import Footer from "./_component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fuzzy = Fuzzy_Bubbles({
  subsets: ["latin"],
  weight: ["400", "700"], // available weights
  variable: "--font-fuzzy",
});
const amaranth = Amaranth({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-amaranth",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${amaranth.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
