import WhatsAppCategoriesCard from "@/app/_component/WhatsAppCategoriesCard";

export const metadata = {
  title:
    "Best WhatsApp Status Collection | Funny, Birthday, Love, Attitude & More",
  description:
    "Browse our huge collection of WhatsApp statuses by category. Funny, birthday wishes, love, sad, motivational, and more — ready to copy and use instantly!",
  keywords: [
    "WhatsApp status categories",
    "funny WhatsApp status",
    "birthday WhatsApp wishes",
    "attitude status for WhatsApp",
    "motivational status",
    "prebuilt WhatsApp statuses",
  ],
  openGraph: {
    title: "WhatsApp Status Collection by Category | Simply Coder",
    description:
      "Get the best WhatsApp status messages organized by category — funny, love, sad, birthday & more. Just copy & share!",
    url: "https://yourdomain.com/whatsapp-status-library",
    siteName: "Simply Coder",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Top WhatsApp Statuses by Category | Copy & Share",
    description:
      "Browse 1000+ prewritten WhatsApp statuses in multiple categories. Add spice to your status today!",
  },
};

const categories = [
  {
    title: "🎉 Birthday Wishes",
    subcategories: {
      "For Best Friend": [
        "Happy Birthday to my partner in crime — may our laughs never end! 😄🎉",
        "You’re more than a friend — you’re my chosen family. Love you always! 💕",
        "Cheers to another year of crazy adventures with my favorite human! 🥂",
        "Life’s way better with you in it — thanks for being you. Happy B’day! 🎈",
        "Through thick and thin, you’ve been my rock. Today, we celebrate you! 🪨❤️",
        "Best friends like you don’t come with a price — you’re priceless! 💎",
        "From secrets to memories, we’ve shared it all — and I wouldn’t change a thing. 🥳",
        "Your happiness means the world to me. Let’s make today epic! 🌍🎉",
        "Growing older is cooler with you by my side. Happy Birthday, soul twin! 🔥",
        "May your dreams soar as high as our friendship has flown. 🎂🕊️",
      ],
      "For Mother": [
        "Happy Birthday to the heart of our home — love you always, Mom! 💖🏡",
        "Your love is my forever warmth. Have the most beautiful birthday, Maa! 🌸🎂",
        "Thanks for every hug, meal, and word of wisdom. Today is all yours! 🫶🎉",
        "To the queen of care and comfort — you deserve the world today. 👑🌍",
        "You make life softer, warmer, and sweeter. Happy Birthday, Mom! 🍰💐",
        "Every moment with you is a blessing. Celebrate with joy, Mumma! 🥳🙏",
        "Wishing peace, love, and a little pampering to the one who gives it all. 🧘‍♀️💝",
        "Your smile lights up my life. Shine brighter than ever today! ✨🌺",
        "You gave me everything without asking. Today, I give you all my love. 🎁❤️",
        "Mothers like you are rare and precious — Happy Birthday to the best! 💎🎈",
      ],
      "For Father": [
        "Happy Birthday to the man who taught me strength and kindness. 💪❤️",
        "Your wisdom is my guiding light — have a wonderful birthday, Dad! 🎂✨",
        "Thanks for always being my superhero, even without a cape. 🦸‍♂️🎉",
        "You make fatherhood look effortless — love you forever, Dad! 🧡",
        "May your birthday be filled with peace, pride, and a little mischief. 😄",
        "To the one who gave me roots and wings — Happy Birthday, Papa! 🌳🕊️",
        "Every lesson you taught me made me who I am. Have a beautiful day! 📘🌟",
        "Dad, you’re my anchor and my inspiration. Celebrate big today! ⚓🎁",
        "Here’s to your strength, love, and timeless dad jokes! 😂🎈",
        "On your special day, I just want to say: You’re my greatest role model. 👏💙",
      ],
      "For Child(Son/Daughter)": [
        "Happy Birthday, little star! Keep shining bright and chasing dreams. 🌟🎂",
        "Wishing you a magical day full of laughter, surprises, and cake! 🎉🧁",
        "To the cutest smile and the brightest spirit — Happy Birthday, champ! 😄🎈",
        "May your day be filled with balloons, giggles, and lots of love! 🎈💖",
        "Watching you grow is the greatest joy. Have a fun-tastic birthday! 🛝🎊",
        "Big hugs and even bigger wishes for the birthday superstar! 🌟🤗",
        "You light up every room, little one. Today, we celebrate your sparkle! ✨🎁",
        "Keep dreaming, keep exploring, keep being amazing. Happy Birthday! 🚀🎂",
        "A year older, a whole lot cuter! Wishing you endless fun today! 🧸🍰",
        "To our tiny bundle of joy — may your day be as sweet as you! 🍬🎉",
      ],
    },
  },
  {
    title: "❤️ Love & Romantic",
    subcategories: {
      General: [
        "Every love story is special, but ours is my favorite. ❤️✨",
        "You're not just my heart, you're my home. 🏡💕",
        "Loving you feels like breathing — effortless and essential. 🌬️💘",
        "I found my forever in your smile. 😊💖",
        "You're the reason my heart beats a little faster. 💓🔥",
        "With you, even silence feels like poetry. 🥰📖",
        "My favorite place in the world is right next to you. 🌍💑",
        "You + Me = Endless magic. 💫👫",
        "Every time I see you, I fall in love all over again. 💘👀",
        "You’re my today, my tomorrow, and every heartbeat in between. 🕰️❤️",
        "Even the stars envy the sparkle in your eyes. ✨👀",
        "If I know what love is, it's because of you. 🫀",
        "You make my world brighter just by being in it. 🌟",
        "When I’m with you, time stops and hearts speak. 💞",
        "You're the melody my heart has been humming forever. 🎶💓",
        "Our souls met long before our eyes did. 🌌",
        "In your arms, I’ve found both peace and fire. 🔥🕊️",
        "I still get butterflies every time I see you. 🦋😍",
        "With you, every ordinary moment feels extraordinary. ✨",
        "My heart chose you, and it's the smartest thing it ever did. 🧠❤️",
        "You're the dream I never want to wake up from. 🌙💤",
        "Holding your hand feels like holding the world. 🌎✋",
        "Love isn't something I fall into, it's someone I grow with — you. 🌱❤️",
        "You're my sweetest escape and my greatest reality. 🍯🌈",
        "You're not my number one, you're my only one. 🔐💘",
        "In your smile, I see a thousand sunrises. 🌅😊",
        "Loving you is like breathing — I just can't stop. 💨❤️",
        "You're the reason my heart whispers 'stay.' 🤫💓",
        "If love had a face, it would look just like yours. 🥰🖼️",
        "Forever isn't long enough when it comes to us. 🔁💖",
        "Your voice is my favorite sound, your name is my favorite word. 🎧💬",
        "You're the pause in my chaos, the calm in my storm. 🌧️🌈",
        "I didn’t believe in fate until you happened. 💫👩‍❤️‍👨",
        "You’ve turned my life into a beautiful love song. 🎵❤️",
        "My soul recognized yours the moment we met. 🔄💞",
        "I love you more than I have words to say — and that’s saying something. 💬❣️",
        "Our hearts speak a language only we understand. 💑🔐",
        "No moment with you is ever wasted; it’s all memory in the making. 🕰️💖",
        "You're the peace I never knew I needed. ☮️💓",
        "With you, my love, every day feels like Valentine's. 🌹💌",
        "Your laughter is my favorite love song. 🎶😂❤️",
        "Distance means nothing when someone means everything. 🌍📏",
        "I want to grow old with you and laugh at all the memories we create. 👵👴📸",
        "You are the sunshine that makes my soul bloom. 🌻🌞",
        "You walked in, and suddenly, everything made sense. 🚪💡",
        "You’re the missing piece I didn’t even know I was looking for. 🧩💘",
        "Every love poem I’ve read now finally makes sense — because of you. 📖💖",
        "I’d choose you in every life, in every world, in every heartbeat. 🌌💓",
        "You're not just my love — you're my light, my fire, and my forever. 🔥✨❤️",
        "In your love, I’ve found my reason, my rhythm, and my rest. 🎵🫶",
      ],
    },
  },
  {
    title: "🤝 Friendship",
    subcategories: {
      General: [
        "Friends are the family we choose ourselves. 🫂❤️",
        "With true friends, even silence is comforting. 🤫👬",
        "Good times + Crazy friends = Amazing memories. 🎉😂",
        "You make life brighter just by being in it. 🌟👯‍♂️",
        "Real friends don’t let you do stupid things… alone. 😜🤝",
        "A friend is one soul living in two bodies. 🧠💞",
        "Loyal friends are rare — like diamonds in a sea of stones. 💎🌊",
        "We didn’t realize we were making memories, we just knew we were having fun. 📸😄",
        "True friendship is a journey without an end. 🚶‍♂️🚶‍♀️💫",
        "No road is long when you walk with a friend. 🛣️👫",
        "Friends multiply your joy and divide your sorrow. ➕❤️➖",
        "Real friends are like stars — you don’t always see them, but they’re always there. 🌌✨",
        "You’re my person, my laughter, my chaos, my calm. 💥😌",
        "Friendship isn’t about who you’ve known the longest; it’s about who walked in and stayed. 🚪🤗",
        "Life is better with friends and snacks. 🍿😄",
        "Behind every great memory is a bunch of crazy friends. 📚😂",
        "Cheers to the ones who know all your weirdness and still stick around. 🥂😜",
        "Friendship is the art of keeping hearts close, no matter how far apart. 🗺️💓",
        "Some friendships are timeless — like vintage wine and old jokes. 🍷😂",
        "The best mirror is an old friend. 🪞👴",
        "Friendship: when your nonsense makes sense to someone else. 🤪🤝",
        "My friend is my sunshine on a cloudy day. ☀️🌧️",
        "You laugh, I laugh. You cry, I cry. You jump off a cliff, I say ‘wait, what?’ 😳😆",
        "A best friend knows your stories. A true friend helped you write them. ✍️📖",
        "Friendship is born when one says, ‘You too? I thought I was the only one!’ 🤯❤️",
        "Friends are the music to our life’s dance. 🎶💃",
        "When you can’t look on the bright side, your friend sits with you in the dark. 🌚🪑",
        "True friendship doesn’t need daily conversation — just loyalty and love. 📵💞",
        "Friends are those who make your problems their problems. 🤝🧠",
        "A real friend is one who walks in when the rest of the world walks out. 🚶‍♂️🚪",
        "You bring the spark to my sarcasm and the calm to my chaos. 🔥😅",
        "With you, even the boring days feel like adventures. 🗺️😊",
        "My friend, you are the reason I smile a little more every day. 😊👯",
        "The most valuable antique is an old friend. 🧓📦",
        "True friends lift you higher — not bring you down. 🪁🙌",
        "Our friendship is proof that crazy attracts crazy. 😜👯‍♀️",
        "You know too much to ever leave. 😏🔐",
        "Best friends make good times better and hard times easier. 💪❤️",
        "If friendship was a currency, I’d be a billionaire with you. 💸👭",
        "The bond we share is louder than words. 🔗🤐",
        "A friend is someone who listens even when you don’t make sense. 👂😅",
        "My favorite therapy is a chat with my best friend. 🛋️📱",
        "Friendship is the comfort of knowing you’re never alone. 🌈🤗",
        "Our friendship: part comedy, part therapy, all love. 🎭💖",
        "Every inside joke started with a little chaos. 😆💬",
        "True friends see the pain in your eyes even when you're smiling. 👀🙂",
        "Thanks for being the reason I believe in loyalty. 🙏🤝",
        "Best friends: born for the good times, built for the tough ones. 🏗️❤️",
        "Friendship is the heartbeat of the soul. 🫀🎵",
        "No friendship is an accident — we were meant to cross paths. 🛤️✨",
      ],
    },
  },
  {
    title: "🚀 Motivation",
    subcategories: {
      General: [
        "Push past your limits — that’s where growth begins. 🚀💪",
        "Success starts with the courage to try. 🌟",
        "Don’t wait for inspiration. Be your own spark. 🔥",
        "You’re stronger than the excuses holding you back. 🛑➡️🏋️",
        "One step at a time still gets you closer. 👣",
        "The only bad day is the one you gave up. ❌📆",
        "Discipline beats motivation every single day. 🕰️🎯",
        "Every morning is a blank page. Write a good story. 📖🌅",
        "Your future depends on what you do today. ⏳💡",
        "Fall seven times, stand up eight. 🥊🧍",
        "If it scares you, it might be worth doing. 😨➡️🎉",
        "Big dreams need bold actions. 🎯🚶‍♂️",
        "Don’t limit your challenges. Challenge your limits. 🧠🔥",
        "Work in silence. Let success make the noise. 🤫📣",
        "The grind will never betray you. 💼🧱",
        "Impossible is just an opinion. 🧠🚫",
        "Consistency is what transforms average into excellence. 🔁✨",
        "Success is a series of small efforts, repeated daily. 📆🪜",
        "Winners are not people who never fail — they are people who never quit. 🏆🙅‍♂️",
        "Hard work beats talent when talent doesn’t work hard. 💪🧠",
        "You’re one decision away from a totally different life. 🔄🔑",
        "Your comfort zone is a beautiful place, but nothing ever grows there. 🌱🛋️",
        "Focus on progress, not perfection. 🎯📈",
        "Hustle until your haters ask if you’re hiring. 🧢💼",
        "When you feel like quitting, remember why you started. 🛑🔁",
        "It’s not about having time. It’s about making time. ⏰🛠️",
        "Your mindset is your strongest muscle. Train it daily. 🧠🏋️‍♂️",
        "The best view comes after the hardest climb. 🏞️🧗‍♂️",
        "Success isn’t lucky — it’s earned. 💼🔥",
        "You’ve got what it takes. But it’ll take everything you’ve got. 🎒⚡",
        "Turn your can’ts into cans and your dreams into plans. ✅📌",
        "Wake up. Kick butt. Repeat. 🔁💥",
        "You are the author of your own comeback story. ✍️📘",
        "Small actions every day lead to big changes. 🔄📊",
        "The struggle is part of the story. 🥀➡️🌹",
        "Discomfort is a sign of progress. 🌀➡️💪",
        "Don’t stop until you’re proud. 😤🏁",
        "Train like you’re the underdog. Win like you’re the champ. 🥇🐶",
        "Make today so awesome, yesterday gets jealous. 😎🔥",
        "The harder you work, the luckier you get. 🍀💼",
        "Be the energy you want to attract. ⚡🌌",
        "Stay focused. Stay fierce. Stay unstoppable. 🧘‍♂️🐅🚀",
        "Worry less. Do more. Win big. 🧠✅🏆",
        "Success is 1% inspiration, 99% perspiration. 💡💧",
        "Believe in your hustle like it already worked. 🙌📈",
        "Keep going. Your future self is already cheering you on. 📣👤",
        "What you do today decides who you become tomorrow. ⏳👊",
        "Let your ambition be louder than your fear. 📢🕷️",
        "You didn’t come this far just to stop here. 🚧🚶",
        "The best way out is always through. 🔁🏃‍♂️",
      ],
    },
  },
  {
    title: "😢 Sad & Emotional",
    subcategories: {
      General: [
        "Sometimes the silence is louder than words.",
        "It’s okay to feel broken sometimes; it means you’re human.",
        "Behind every smile, there’s a story of pain.",
        "Tears are words the heart can’t express.",
        "Feeling lost in a world that keeps moving on.",
        "Some wounds don’t show, but they hurt the most.",
        "Loneliness is a silent companion.",
        "Pain makes you stronger, but it also makes you quiet.",
        "It’s hard to forget someone who gave you so much to remember.",
        "When you feel alone, remember the stars still shine for you.",
        "Not every story has a happy ending.",
        "Broken hearts still beat, but with more caution.",
        "Sometimes love isn’t enough to keep us together.",
        "The hardest part is learning to let go.",
        "Sadness is the price we pay for loving deeply.",
        "My heart is tired but keeps beating.",
        "The darkest nights produce the brightest stars.",
        "I smile to hide the pain I feel inside.",
        "Grief is the silent echo of love lost.",
        "Sometimes, the strongest people cry in silence.",
        "Memories can hurt more than reality.",
        "Falling apart doesn’t mean you’re weak.",
        "Lost in thoughts, drowning in emotions.",
        "Some scars are invisible, but they never fade.",
        "It’s okay not to be okay.",
        "The pain you feel today will be your strength tomorrow.",
        "In the end, we all have to face our own battles alone.",
        "Heartbreak teaches us the true meaning of strength.",
        "I’m silently fighting a war you know nothing about.",
        "When words fail, tears speak.",
        "It hurts when someone you trust becomes a stranger.",
        "The weight of sadness is heavy but invisible.",
        "Sometimes the hardest goodbye is the one you never said.",
        "Even the strongest storms eventually pass.",
        "Pain is inevitable, suffering is optional.",
        "Happiness feels so far when sadness takes over.",
        "Letting go is the hardest thing to do.",
        "The loneliest place is inside your own mind.",
        "Sometimes, all you can do is breathe and keep going.",
        "Emotions are messy, but they keep us real.",
        "I’m broken, but still standing.",
        "The heart remembers what the mind tries to forget.",
        "Sadness is a visit, not a permanent resident.",
        "Wounds heal, but memories stay.",
        "It’s okay to cry and not be strong all the time.",
        "Pain teaches us lessons we didn’t ask for.",
        "Sometimes, healing is a quiet process.",
        "The night feels colder when you’re alone.",
        "In the silence, I find my strength.",
      ],
    },
  },
  {
    title: "🔥 Attitude",
    subcategories: {
      General: [
        "I don’t follow the crowd; I make my own path.",
        "Confidence is silent, insecurities are loud.",
        "Not everyone likes me, but not everyone matters.",
        "I’m not arrogant, I’m just aware of my worth.",
        "My attitude depends on how you treat me.",
        "I’m not here to please everyone, I’m here to be myself.",
        "Strong minds discuss ideas, weak minds discuss people.",
        "I’m too busy working on my own grass to notice if yours is greener.",
        "Don’t mistake my kindness for weakness.",
        "I’m not perfect, but I’m always real.",
        "I don’t compete, I dominate.",
        "Hustle until your haters ask if you’re hiring.",
        "I’m the energy I want to attract.",
        "Keep rolling your eyes, maybe you’ll find a brain back there.",
        "Some call it attitude, I call it confidence.",
        "I’m not cocky, I’m just better than you think.",
        "I don’t have an attitude problem, I have a personality you can’t handle.",
        "I’m not here to be average, I’m here to be awesome.",
        "I don’t follow trends, I set them.",
        "I’m on my own vibe, you’re on yours.",
        "They told me I couldn’t, that’s why I did.",
        "Stay humble, but let your attitude shine.",
        "I’m not rude, I’m honest.",
        "Life gave me lemons, I made a lemonade empire.",
        "If you don’t like my attitude, quit talking to me.",
        "I don’t need your approval to be me.",
        "I’m not difficult, I’m just not easy to forget.",
        "I’m the CEO of my own life.",
        "Attitude is everything — pick a good one.",
        "I’m unapologetically me.",
        "Not everyone gets my vibe, and that’s okay.",
        "I’m a limited edition; there’s no duplicate.",
        "I’m not a backup plan, and definitely not your second choice.",
        "Stay classy, but be savage when needed.",
        "I don’t do drama, I do karma.",
        "Your opinion of me doesn’t define me.",
        "I’m too original to be copied.",
        "I’m the storm they didn’t see coming.",
        "I’m my own competition.",
        "I’m the author of my own story.",
        "I’m not a player, I’m the game changer.",
        "My attitude speaks louder than words.",
        "I’m not here to fit in, I’m here to stand out.",
        "I don’t chase, I attract.",
        "If you want to fly, you have to give up what weighs you down.",
        "I’m built from mistakes and lessons learned.",
        "I’m the vibe you wish you had.",
        "I don’t quit; I reset.",
        "I’m the energy you can’t ignore.",
        "Confidence level: Self-made.",
        "I’m not arrogant, I’m just confident.",
        "Keep my name out of your mouth unless you’re ready to be a fan.",
      ],
    },
  },
];

export default function page() {
  return (
    <section className="w-full min-h-screen py-20 px-6 bg-gradient-to-br from-white via-green-50 to-emerald-100 ">
      <div className="max-w-4xl mx-auto mt-10">
        <h1 className="text-4xl font-bold text-center text-emerald-700 mb-12">
          📚 WhatsApp Status by Category
        </h1>

        <WhatsAppCategoriesCard categories={categories} />
      </div>
    </section>
  );
}
