export const contentData = {
  "sad-quotes": {
    title: "Sad Quotes",
    description:
      "Sometimes, words help where silence fails. This collection of sad quotes captures the raw emotions of heartbreak, loneliness, and silent pain — crafted to help you feel seen, understood, and less alone. Whether you're sharing your feelings or just reading to reflect, these lines are here for you.",
    keywords:
      "sad quotes, emotional quotes, heartbreak, sorrow, grief, pain, unhappy, depressing quotes, deep sad quotes",
    content: [
      "Smiles hide the stories we’re too broken to tell.",
      "Sometimes silence screams louder than tears ever could.",
      "I pretend to be okay because explaining why I’m not is exhausting.",
      "Losing someone isn’t just about absence — it’s about carrying their echo everywhere.",
      "The worst goodbyes are the ones left unspoken.",
      "Every unread message feels like a goodbye I didn’t expect.",
      "Sadness doesn’t shout — it sits quietly and takes root.",
      "Healing isn’t about forgetting; it’s about forgiving the hurt without reliving it.",
      "I scroll through memories like chapters I can’t rewrite.",
      "Sometimes the hardest battles are the ones you fight alone in your own mind.",
      "Even broken hearts keep beating — that’s the cruelest part.",
      "The moon understands loneliness more than the sun ever will.",
      "Tears don’t make you weak; they make you real.",
      "We outgrow people, but never the feelings they leave behind.",
      "Some nights, even the stars feel distant.",
      "Grief doesn’t knock — it walks in, uninvited, and stays.",
      "I miss the version of me that didn’t know what heartbreak felt like.",
      "Pain has no timestamp — it just lingers until it fades.",
      "I keep deleting messages I wish I could send.",
      "Not every connection deserves a second chance — even if your heart says otherwise.",
      "They moved on like nothing happened; I’m still picking up pieces.",
      "When people leave, it’s the silence that screams the loudest.",
      "I never wanted perfect — I just wanted honest.",
      "The more I cared, the more invisible I became.",
      "Healing isn’t linear — it curves through chaos and quiet.",
      "It’s strange how someone can feel like home and a stranger at the same time.",
      "Sadness doesn’t fade — it just gets quieter.",
      "I’m not afraid of being alone. I’m afraid of being forgotten.",
      "Trust is fragile — once broken, even love can’t always fix it.",
      "I wear happiness like armor; underneath, I’m just surviving.",
    ],
  },
  "heartbroken-quotes": {
    title: "Heartbroken Quotes",
    description:
      "Discover heartfelt and deeply original heartbroken quotes that capture the raw emotions of love and loss. Whether you're healing from a breakup or just need words to express your pain, these quotes offer comfort, reflection, and emotional strength. Perfect for sharing, reading, and finding peace through honest expressions of heartbreak.",
    keywords:
      "heartbreak, broken heart, love loss, emotional pain, healing, breakup quotes, sad love, shattered heart",
    content: [
      "You promised forever, but left me with echoes of goodbye.",
      "My heart remembers the touch you forgot.",
      "We talked like soulmates and ended like strangers.",
      "I gave you pieces of me you never planned to keep.",
      "You left, but your absence still lingers louder than your presence ever did.",
      "The hardest part isn’t letting go — it’s pretending I already have.",
      "My chest still aches where your name used to live.",
      "I deleted the messages, but not the memories.",
      "I miss us — the 'us' you forgot too easily.",
      "I saw forever in your eyes. You only saw temporary in mine.",
      "Some hearts break quietly, like mine did for you.",
      "You moved on with ease. I’m still rewriting the goodbye.",
      "We stopped talking, but you never stopped echoing in my thoughts.",
      "You taught me love, then showed me loss.",
      "I’m not healing — just hiding the hurt better.",
      "It’s not the ending that hurts — it’s the unfinished dreams.",
      "You were a chapter I reread until the pain became familiar.",
      "I was all in — you were already halfway out.",
      "The cruelest breakups are the ones where no one says goodbye.",
      "You held my heart, then dropped it like it meant nothing.",
      "I watched us fall apart in slow motion — and you didn’t blink.",
      "The silence you left behind is louder than your lies.",
      "Your love was a storm I mistook for shelter.",
      "You were once my peace — now you're my pain.",
      "I kept holding on while you let go without a second thought.",
      "I wasn't hard to love — you just stopped trying.",
      "What broke me wasn’t your leaving — it was your ease in doing so.",
      "You were my favorite mistake — and the most painful one.",
      "We had potential. You had excuses.",
      "You promised to stay — I believed you. That was my first heartbreak.",
    ],
  },
  "alone-status": {
    title: "Alone Status",
    description:
      "Explore the depth of solitude with our original alone status lines that speak straight to the heart. Whether you’re embracing peace or processing pain, these meaningful statuses help express the quiet strength and emotions that come with being alone. Perfect for WhatsApp, Instagram, or when you just need to feel understood.",
    keywords:
      "alone status, solitude, independence, self-discovery, peace, quiet, introverted, self-love, embracing loneliness",
    content: [
      "Alone isn't empty — it's where I find my peace.",
      "I’m surrounded, yet solitude is my only companion.",
      "Being alone taught me the value of my own silence.",
      "Not lonely, just tired of temporary people.",
      "In the quiet, I hear the truth I ignored in the noise.",
      "Alone doesn’t mean broken — it means rebuilding.",
      "I stopped chasing people and started finding myself.",
      "Sometimes being alone feels safer than being misunderstood.",
      "I’m not alone — I’m just unreachable to those who never cared.",
      "Peace begins the moment you embrace solitude.",
      "They left, and I discovered who really stays — me.",
      "Loneliness hurts, but pretending doesn’t heal.",
      "I smile more when I’m alone — no one expects anything.",
      "Being alone showed me how crowded fake love was.",
      "Alone, but never without my thoughts — and they’re louder than ever.",
      "The worst feeling isn’t being alone, it’s being forgotten.",
      "Solitude is the only place where I feel whole lately.",
      "I’ve learned more from silence than from any conversation.",
      "People come and go, but my shadow has always stayed.",
      "I stopped asking who’s staying — I just learned to walk alone.",
      "Sometimes, silence is the only reply that makes sense.",
      "The world never noticed my quiet exits.",
      "I’m alone by choice, not because I’m unwanted.",
      "I’ve mastered the art of being okay on my own.",
      "Solitude is where I rebuild the pieces they shattered.",
      "I feel lighter when I’m not carrying anyone else’s expectations.",
      "Lonely nights taught me strength the world never gave.",
      "I’m not lost — just wandering on a path only I can walk.",
      "It’s better to sit alone than to fake a smile with wrong company.",
      "Being alone isn’t sad — pretending I’m not was worse.",
    ],
  },
  "missing-quotes": {
    title: "Missing Someone",
    description:
      "Missing someone can be a silent ache, and these heartfelt quotes give words to that feeling. Whether it's a loved one far away or a memory that lingers, our original missing quotes help you express the emotions that come with distance and longing — perfect for sharing on WhatsApp, Instagram, or keeping close to the heart.",
    keywords:
      "missing someone, longing, love, distance, remembrance, absence, heartfelt, thinking of you, yearning",
    content: [
      "Your memories always stay close to my heart.",
      "Even miles apart, I feel your presence near me.",
      "I feel your absence every single moment.",
      "Waiting for you, even when you’re far away.",
      "I keep remembering your smile and words again and again.",
      "Life feels incomplete when you’re not by my side.",
      "Everything feels empty without you here.",
      "My heartbeat only says your name all the time.",
      "Living without you is the hardest truth I face.",
      "I meet you in my dreams every night.",
      "Lost in your memories day and night.",
      "There’s a void in my life since you left.",
      "The hope to see you never fades away.",
      "Thinking about you every moment.",
      "The scent of your memories still surrounds me.",
      "Your friendship and memories keep me alive.",
      "Come back someday, you will be missed.",
      "Even apart, I feel your love deeply.",
      "No one can fill the space you left behind.",
      "This journey feels incomplete without you.",
      "Every night your picture comes alive in my dreams.",
      "Life feels deserted without your memories.",
      "Meeting you again is my biggest wish.",
      "I can’t imagine living without you.",
      "Everything feels worthless after you left.",
      "My tears flow rivers thinking about you.",
      "No joy is complete without you.",
      "My heart cries when I remember you.",
      "Though far, I feel your support around me.",
      "This heart feels empty without you.",
    ],
  },
  "love-quotes": {
    title: "Love Quotes",
    description:
      "Love is the language of the heart — and our handpicked love quotes capture its magic in every word. Whether you're falling in love, cherishing someone special, or simply want to share a sweet thought, these original lines are perfect for expressing deep emotions on social media or in private messages.",
    keywords:
      "love quotes, romantic quotes, true love, affection, devotion, relationship goals, couple quotes, heartfelt love, passion",
    content: [
      "Love isn’t just a feeling — it’s a beautiful choice we make every day.",
      "True love grows deeper in the smallest moments shared together.",
      "You don’t find love, love finds you when you’re ready to give it.",
      "In your smile, I found the home I never knew I needed.",
      "Love is the silent promise that never needs words.",
      "When love is real, even distance feels like closeness.",
      "Loving you taught me how to see the world in brighter colors.",
      "A heart that loves freely, never knows loneliness.",
      "Love is the spark that turns ordinary days into magic.",
      "With you, I’m not just alive — I’m truly alive.",
      "Love is not about possession but about appreciation.",
      "Every heartbeat whispers your name in a language only I understand.",
      "True love doesn’t fade with time — it grows stronger through it.",
      "You’re my favorite ‘hello’ and my hardest ‘goodbye.’",
      "Love is the art of growing together, even when apart.",
      "The best love stories are written with trust and kindness.",
      "You are the calm to my storm and the light in my darkness.",
      "Loving you is the easiest decision my heart ever made.",
      "Every love begins with a simple ‘yes’ and endless hope.",
      "Love’s greatest power is healing even the deepest wounds.",
      "I don’t need perfect — I just need you, perfectly real.",
      "Love teaches us patience, forgiveness, and courage.",
      "You’re the song my heart hums when the world gets quiet.",
      "Love is not finding someone to live with, but someone you can’t live without.",
      "Our souls recognized each other before we even met.",
      "In your arms, I found my safest place on earth.",
      "True love is feeling at home, no matter where we are.",
      "Loving you feels like a beautiful journey without an end.",
      "You’re my everyday magic and my forever inspiration.",
      "Love is a story we write together — page by page, heart by heart.",
    ],
  },
  "romantic-status": {
    title: "Romantic Status",
    description:
      "Fall in love with words that speak from the heart. Our original love quotes beautifully express affection, care, and emotional connection — perfect for messages, bios, captions, or status updates. Whether you're in a new relationship or celebrating timeless love, these quotes help say what words often can't.",
    keywords:
      "romantic status, love status, sweet messages, couple goals, relationship quotes, romantic captions, affection, dating",
    content: [
      "Every moment with you feels like a beautiful dream I never want to wake from.",
      "Your love is the light that brightens even my darkest days.",
      "With you, every heartbeat sings a song of forever.",
      "You are my today, my tomorrow, and all the days after.",
      "Love is not just in the words we say, but in the way we look at each other.",
      "Holding your hand makes the world feel right.",
      "You’re the reason my smile is brighter every day.",
      "In your arms, I found my forever home.",
      "Our love story is my favorite fairytale come true.",
      "With you, every second feels like a lifetime of happiness.",
      "Your love is the sweetest melody in the soundtrack of my life.",
      "Forever isn’t long enough when I’m with you.",
      "You are my heartbeat, my soul’s perfect rhythm.",
      "Every love song suddenly makes sense because of you.",
      "With you, even silence speaks volumes of love.",
      "You’re the best part of every day and every night.",
      "Together, we make ordinary moments extraordinary.",
      "I didn’t just find love — I found my best friend.",
      "You’re my favorite hello and the hardest goodbye.",
      "In your eyes, I see a future full of endless love.",
      "Love grows deeper when it’s shared with you.",
      "You complete the pieces of my heart I didn’t know were missing.",
      "Being with you feels like home and adventure all at once.",
      "Your love is my sweetest addiction, my beautiful habit.",
      "I promise to love you more with every sunrise and sunset.",
      "You’re the spark that ignites my soul every day.",
      "Every kiss from you feels like the first and the last.",
      "My heart beats in sync with yours, forever intertwined.",
      "Loving you is my favorite thing to do, every single day.",
      "You’re not just my love; you’re my everything.",
    ],
  },
  "attitude-status": {
    title: "Attitude Status",
    description:
      "Level up your vibe with bold and original attitude status lines that show your confidence and mindset. Whether you're handling hate or owning your goals, these captions let your personality speak loud and clear. Perfect for bios, social media, and WhatsApp statuses that leave a mark.",
    keywords:
      "attitude status, confidence, strong mindset, self-belief, bold, personality, savage, independent, fearless, boss moves",
    content: [
      "Confidence is silent, insecurities are loud.",
      "I don’t follow the crowd, I lead my own way.",
      "My attitude is based on how you treat me.",
      "I’m not rude, I’m just honest with a sharp edge.",
      "Don’t mistake my kindness for weakness.",
      "Success is the best revenge for haters.",
      "I’m not perfect, but I’m always real.",
      "My vibe attracts my tribe.",
      "I’m too busy working on my own greatness to care about yours.",
      "Respect is earned, not given.",
      "I don’t chase dreams, I hunt goals.",
      "I’m not here to please everyone, just myself.",
      "Attitude is everything — mine is unstoppable.",
      "I’m a limited edition, there’s no copy of me.",
      "Stay strong, make them wonder how you’re still smiling.",
      "I don’t compete, I dominate.",
      "Hustle in silence, let your success make the noise.",
      "Some people want it to happen, I make it happen.",
      "I’m not arrogant, I’m just aware of my worth.",
      "Keep your head high and your middle finger higher.",
      "My attitude is my power, don’t underestimate it.",
      "I’m not here to be average, I’m here to be awesome.",
      "Born to stand out, never to fit in.",
      "I don’t need your approval to be me.",
      "Real queens fix each other’s crowns.",
      "I’m the CEO of my own life.",
      "Attitude is the difference between an ordeal and an adventure.",
      "I’m too original to be a copy.",
      "Don’t like my attitude? Go buy one.",
      "I’m not lucky, I’m skilled and focused.",
    ],
  },
  "flirty-captions": {
    title: "Flirty Captions",
    description:
      "Turn up the charm with playful and cheeky flirty captions that say just enough to spark interest. Whether you’re dropping a wink or teasing with a smile, these captions add fun and flirtation to your selfies and stories—perfect for catching eyes on Instagram, WhatsApp, or anywhere you post.",
    keywords:
      "flirty captions, charming, witty, playful, attractive, playful captions, dating, pick up lines, confident",
    content: [
      "Is it just me, or did it just get a little hotter in here? 🔥😉",
      "Are you a magician? Because whenever you’re around, everything else disappears. ✨❤️",
      "Do you believe in love at first swipe? Because I just did. 💕📱",
      "You must be tired, ‘cause you’ve been running through my mind all day. 😜💭",
      "Flirting is my cardio. Care to join? 💃🕺",
      "Your smile should come with a warning label—dangerously charming! 😍⚠️",
      "Can I follow you home? Cause my parents always told me to follow my dreams. 😉🏡",
      "If kisses were snowflakes, I’d send you a blizzard. ❄️😘",
      "Are you a camera? Because every time I look at you, I smile. 📸😊",
      "I’m not a photographer, but I can definitely picture us together. 📷❤️",
      "Warning: flirting with me may cause butterflies and heart palpitations. 🦋💓",
      "Is your name Google? Because you’ve got everything I’ve been searching for. 🔍💖",
      "I’m not flirting, I’m just being extra friendly to someone who’s extra cute. 😘✨",
      "Do you have a map? I keep getting lost in your eyes. 🗺️👀",
      "Are we at the airport? Because my heart is taking off every time you smile. ✈️💘",
      "You’re the reason I check my phone so much. 📱💬",
      "If I had a star for every time you brightened my day, I’d have a galaxy. 🌟🌌",
      "I’m not saying you’re my favorite, but you’re definitely in the top one. 😉💕",
      "Flirting level: expert. Wanna be my study partner? 📚❤️",
      "I’m just a cupcake looking for a stud muffin. 🧁😏",
      "You must be a spark, because you light up my world. ✨🌍",
      "I’m not trying to be charming, it just comes naturally around you. 😌❤️",
      "Can you hold this? *hands you my heart* 💓😇",
      "Are you a time traveler? Because I see my future with you. ⏳💑",
      "If flirting was a sport, I’d be a gold medalist. 🥇😉",
      "You must be caffeine, because you keep me awake all night. ☕🌙",
      "I’m no mathematician, but you and me add up perfectly. ➕❤️",
      "Is it hot in here or is it just our chemistry? 🔥⚗️",
      "You had me at ‘Hello.’ 😘👋",
      "Let’s make this chat more interesting, shall we? 😉💬",
    ],
  },
  "good-morning-messages": {
    title: "Good Morning Messages",
    description:
      "Start the day with warmth and positivity through thoughtful good morning messages. Whether you're wishing someone special, sending motivation to a friend, or simply spreading sunshine, these messages are perfect for brightening inboxes and social feeds with a smile.",
    keywords:
      "good morning, morning greetings, positive start, inspiration, fresh day, good vibes, daily motivation, blessings",
    content: [
      "Rise and shine! A new day, a new chance to sparkle. ✨🌞",
      "Good morning! Let your smile be the sunshine today. 😊🌻",
      "Wake up and chase your dreams like the sun chases the horizon. 🌅🔥",
      "Every morning is a fresh start — make it amazing! ☀️💫",
      "Hello, new day! Let’s make magic happen. ✨☕",
      "Good morning! Breathe in positivity, breathe out doubt. 🌬️🌸",
      "Start your day with gratitude and a heart full of hope. ❤️🌞",
      "May your morning be as bright as your spirit. 🌟😊",
      "Coffee in one hand, confidence in the other. Let’s do this! ☕💪",
      "Good morning! Remember, you have the power to make today great. 🌈✨",
      "Sunrise is proof that every day can be beautiful. Embrace it! 🌅❤️",
      "New day, new blessings, new opportunities. Good morning! 🌞🙏",
      "Smile! It’s a brand new morning to start fresh and stay positive. 😊🌷",
      "Good morning! Let your thoughts be kind and your heart be open. 💖🌞",
      "Wake up with determination, go to bed with satisfaction. 💪🌙",
      "The best mornings start with a grateful heart. Good morning! 🙏☀️",
      "Good morning! Today is a blank page — write your story with joy. 📖✨",
      "May your morning coffee be strong and your day be smooth. ☕😊",
      "Rise up, start fresh, and see the bright opportunity in each day. 🌅🌟",
      "Good morning! Your vibe attracts your tribe. Stay positive. ✨👫",
      "Let the morning sun fill your soul with energy and peace. 🌞🕊️",
      "Good morning! Life’s a gift — unwrap it with a smile today. 🎁😊",
      "New dawn, new goals, new dreams. Make it count! 🌅🎯",
      "Wake up and be awesome — the world is waiting! 🌍💫",
      "Good morning! Your journey to greatness begins today. 🚀🌞",
      "Every sunrise brings hope. Embrace the day with open arms! 🌄❤️",
      "Good morning! Let kindness be your morning ritual. 💖🌸",
      "Start your day like a boss — confident and unstoppable. 👑🔥",
      "Good morning! Today, choose joy, courage, and love. 🌈💪❤️",
      "The morning sets the tone — make it positive and powerful! ☀️💥",
    ],
  },
  "good-night-messages": {
    title: "Good Night Messages",
    description:
      "End the day on a peaceful and positive note with our collection of heartfelt good night messages. Perfect for sending warm wishes to loved ones or sharing on social media, these messages help spread calm, comfort, and sweet dreams every night.",
    keywords:
      "good night, sweet dreams, peaceful sleep, restful night, evening wishes, comfort, love, moon, stars",
    content: [
      "Good night! May your dreams be peaceful and your heart calm. 🌙✨",
      "Sleep tight and wake up refreshed for a brand new day. 😴🌟",
      "Night whispers calm; let go of today’s worries and rest well. 🌌💤",
      "Stars are shining just to remind you that you’re never alone. ⭐❤️",
      "Close your eyes, breathe deep, and drift into sweet dreams. 🌙💫",
      "Good night! Tomorrow’s a new chance to shine brighter. 🌟🌙",
      "Let the silence of the night bring you peace and strength. 🕊️🌌",
      "Rest well, recharge, and get ready for a beautiful tomorrow. 🌛💖",
      "May your sleep be deep and your worries light. Good night! 🌠😌",
      "Good night! Leave all stress behind and embrace the night’s calm. 🌜🧘",
      "Dream big and rest easy — your potential awaits. 🌟💤",
      "Wishing you a night filled with stars and sweet serenity. ✨🌙",
      "Good night! Let your soul relax and your mind renew. 🌌💛",
      "Sleep peacefully knowing tomorrow holds endless possibilities. 🌞🌙",
      "May the moonlight guide you to the sweetest dreams tonight. 🌕💫",
      "Good night! Let your heart rest and your spirit soar tomorrow. 💖🌠",
      "The night is a canvas; paint it with beautiful dreams. 🎨🌌",
      "Sleep well and wake up stronger than ever. 🌟😴",
      "Good night! The stars are watching over you with love. ✨❤️",
      "Time to close your eyes and recharge your brilliance. 🌙💡",
      "May your night be calm and your dreams inspiring. 🌌✨",
      "Good night! Rest now, your dreams will light the way. 🌠💫",
      "Sleep with a peaceful heart and wake with a grateful soul. 💖🌜",
      "Let the night heal your worries and fill you with hope. 🌙🕊️",
      "Good night! Tomorrow is a fresh page waiting for your story. 📖🌟",
      "Dream softly and let go of everything heavy. 😴🌌",
      "Sleep deep, rise bright — the world needs your light. 🌞🌙",
      "Good night! Your rest is the seed of tomorrow’s success. 🌱💤",
      "May the quiet of the night bring calm to your heart. 🌛🧘‍♂️",
      "Close your eyes and surrender to the beauty of dreams. 🌠💖",
    ],
  },
  "motivational-quotes": {
    title: "Motivational Quotes",
    description:
      "Boost your spirits and stay inspired with our carefully crafted collection of motivational quotes. Whether you need a daily dose of encouragement or powerful words to chase your dreams, these quotes will uplift your mindset and fuel your determination.",
    keywords:
      "motivational quotes, inspiration, success, achievement, perseverance, growth, positive mindset, overcoming challenges, drive",
    content: [
      "Every step forward, no matter how small, brings you closer to your dreams.",
      "Success is built on the courage to start and the strength to keep going.",
      "Believe in your power to turn challenges into opportunities.",
      "Your mindset shapes your reality—choose positivity and growth.",
      "Great things never come from comfort zones. Step out and shine.",
      "Failures are just lessons dressed in disguise—learn and rise.",
      "Consistency and patience are the true keys to lasting success.",
      "Dream big, work hard, stay focused, and never give up.",
      "The only limits that exist are the ones you place on yourself.",
      "Turn your passion into purpose, and your purpose into progress.",
      "Obstacles are the stepping stones that lead to greatness.",
      "Your effort today creates the success story of tomorrow.",
      "Rise each time you fall; resilience is your greatest strength.",
      "Progress, not perfection, is the goal worth striving for.",
      "Surround yourself with those who inspire and challenge you.",
      "Hard work beats talent when talent doesn’t work hard.",
      "Believe you can, and you’re already halfway there.",
      "Success starts with self-belief and relentless determination.",
      "Embrace challenges—they fuel growth and unlock potential.",
      "Focus on your goals, not the distractions around you.",
      "Every setback is a setup for a stronger comeback.",
      "The journey to success begins with a single brave step.",
      "Your dreams deserve your dedication and daily effort.",
      "Stay positive, work hard, and make it happen.",
      "Confidence comes from preparation and perseverance.",
      "Don’t wait for opportunity—create it with action.",
      "The difference between ordinary and extraordinary is effort.",
      "Push your limits; that’s where growth happens.",
      "Success is a marathon, not a sprint—pace yourself wisely.",
      "Keep your eyes on the prize, and never lose your passion.",
    ],
  },
  "one-liners": {
    title: "One-Liners & Punchlines",
    description:
      "Discover the best original one-liners and punchlines to add spark and wit to your conversations. Perfect for social media captions, status updates, or just making people smile with quick, clever sayings that leave a lasting impact.",
    keywords:
      "one-liners, punchlines, funny, witty, clever, humor, jokes, short jokes, quick wit, comedy",
    content: [
      "Dream it. Plan it. Do it.",
      "Hustle in silence, let success make the noise.",
      "Less talk, more action.",
      "Make today so awesome, yesterday gets jealous.",
      "Stay humble. Work hard. Be kind.",
      "Small steps lead to big changes.",
      "Turn your can’ts into cans.",
      "Work hard in silence, shine in public.",
      "Success loves preparation.",
      "Do it with passion or not at all.",
      "Wake up with determination, sleep with satisfaction.",
      "Grind now, glory later.",
      "Push yourself because no one else will.",
      "Good vibes only, hustle always.",
      "Failure is fuel for growth.",
      "Your vibe attracts your tribe.",
      "Be a voice, not an echo.",
      "Don’t stop until you’re proud.",
      "Create your own sunshine.",
      "Stay focused and extra sparkly.",
      "Believe in yourself and magic happens.",
      "The best way out is always through.",
      "Work hard, dream big.",
      "Rise and grind every day.",
      "Success is earned, not given.",
      "Be fearless in the pursuit of what sets your soul on fire.",
      "Dream big. Act bigger.",
      "Make it happen, shock everyone.",
      "Do more than just exist.",
      "Today’s struggles build tomorrow’s strength.",
    ],
  },
  "funny-status": {
    title: "Funny Status",
    description:
      "Lighten up your day with our collection of original funny statuses! Perfect for WhatsApp, Facebook, and Instagram, these witty and humorous lines are designed to bring a smile to everyone’s face. Share the laughter and spread good vibes!",
    keywords:
      "funny status, humor, hilarious, relatable, jokes, witty, comedy, laughter, cheerful, lighthearted",
    content: [
      "I’m not lazy, just on energy-saving mode.",
      "Running late is my cardio.",
      "If there’s a will, I want to be in it.",
      "I’m on a seafood diet—I see food and I eat it.",
      "Life’s too short to be serious all the time. So if you can’t laugh at yourself, call me—I’ll do it for you!",
      "I’m not weird, I’m limited edition.",
      "Common sense is like deodorant. The people who need it most never use it.",
      "My bed and I are perfect for each other, but my alarm clock keeps trying to break us up.",
      "Some people graduate with honors, I am just honored to graduate.",
      "I put the ‘pro’ in procrastinate.",
      "I don’t need a hairstylist, my pillow gives me a new hairstyle every morning.",
      "Why fall in love when you can fall into a pizza?",
      "I’m multitasking: I can listen, ignore and forget all at once.",
      "I whisper ‘WTF’ to myself at least 20 times a day.",
      "I’m not arguing, I’m just explaining why I’m right.",
      "Life is short—smile while you still have teeth.",
      "I tried to be normal once. Worst two minutes ever.",
      "Exercise? I thought you said extra fries!",
      "I’m great at multitasking—I can waste time, be unproductive, and procrastinate all at once.",
      "Some people graduate with honors, I am just honored to graduate.",
      "If you think nobody cares if you’re alive, try missing a couple of payments.",
      "I’m on a whiskey diet. I’ve lost three days already.",
      "If stress burned calories, I’d be a supermodel.",
      "I’m not lazy, I’m on energy-saving mode.",
      "Sarcasm is my love language.",
      "I don’t need an inspirational quote. I need coffee.",
      "I’m not clumsy, the floor just hates me.",
      "I’m not short, I’m fun-sized.",
      "If at first you don’t succeed, then skydiving isn’t for you.",
      "Some people graduate with honors, I am just honored to graduate.",
    ],
  },
  "savage-quotes": {
    title: "Savage Quotes",
    description:
      "Unleash your bold and fearless side with our collection of savage quotes. Perfect for those who speak their mind and aren’t afraid to show their attitude, these powerful lines will help you make a strong statement on social media and beyond.",
    keywords:
      "savage quotes, fierce, unapologetic, confident, bold, witty, strong, powerful, attitude, boss",
    content: [
      "I’m not rude, I’m honest—big difference.",
      "Don’t mistake my kindness for weakness.",
      "My attitude is a result of your behavior.",
      "If you think I’m nasty, wait till you see my secrets.",
      "I don’t have an attitude problem, I have a ‘you’ problem.",
      "I’m not here to fit into your world. I’m here to make my own.",
      "Some people need a high-five. In the face. With a chair.",
      "I don’t sugarcoat—life isn’t sweet.",
      "I’m the queen of my own little world.",
      "You talk behind my back? Good. That means I’m two steps ahead.",
      "I’m not jealous, I’m just better than you.",
      "I don’t need your approval to be me.",
      "I’m too busy working on my own grass to notice if yours is greener.",
      "Keep rolling your eyes, maybe you’ll find a brain back there.",
      "I don’t chase, I replace.",
      "Don’t study me, you won’t graduate.",
      "My silence is my power.",
      "If you think I’m savage, wait till you see my patience run out.",
      "You were my cup of tea, but I drink champagne now.",
      "Don’t get mad, get better.",
      "I’m not heartless, I just learned how to use my heart less.",
      "Throw me to the wolves, and I’ll come back leading the pack.",
      "I don’t have time to hate people who hate me—it’s exhausting.",
      "Some people aren’t loyal, some people are just good actors.",
      "I’m not bitter, I’m just better off without you.",
      "My attitude speaks louder than your words.",
      "If you’re waiting for me to care, you’re going to be waiting a while.",
      "I’m savage, not average.",
      "Be savage, not average.",
      "Better an ‘oops’ than a ‘what if.’",
    ],
  },

  "hindi-shayari": {
    title: "Hindi Shayari",
    description:
      "Dil se nikli hui Hindi Shayari jo chhoo jaaye aapka dil – pyaar, dard, yaadein aur zindagi ke pal, sab kuch ek jagah.",
    keywords:
      "hindi shayari, love shayari, sad shayari, romantic shayari, emotional shayari, life quotes, urdu shayari in hinglish",
    content: [
      "Zakhm dil ke chhupaaye nahi chhoot'te, kuch yaadein yun hi muskuraaye nahi chhoot'ti.",
      "Chaand ki chaandni se nahi, tere pyaar ki roshni se mera jahaan roshan hai.",
      "Tere bina ye shaamein adhoori lagti hain, tere saath har khushi poori lagti hai.",
      "Dard ke saaye mein bhi hans lete hain hum, kyunki jazbaaton ko chhupana aata hai.",
      "Raahon mein bichhadne ka darr to tha, phir bhi tujhse milne ki chahat zinda thi.",
      "Kuch khwaab aise hote hain jo adhoore reh jaate hain, par yaadon ki galiyon mein sada basa jaate hain.",
      "Tere kadmon ki aahat sunkar dil dhadakta hai, tere bina ye dil kabhi nahi rehta.",
      "Khwaabon ke shehar mein teri yaadein deewarein ban gayi, jahan har ek mod par tera naam likha hai.",
      "Zindagi ki is daud mein, teri dosti ek aaraam ki chhaon hai.",
      "Sach kahun to tujhse milne ko dil har roz tarasta hai.",
      "Ishq wo nahi jo saja de, ishq wo hai jo sahara de.",
      "Har shaam teri yaadon ki chaadar mein dhal jaati hai.",
      "Na jaane kyu tera gham hi khushi ban jaata hai.",
      "Har lamha teri yaadon ka safar chalta rehta hai.",
      "Tere bina adhoora sa lagta hai mera dil.",
      "Door rehkar bhi tera ehsas sukoon deta hai.",
      "Jinhein kabhi humne khoya, wo hamesha dil ke kareeb rehte hain.",
      "Tere bina ye zindagi kuch bhi nahi.",
      "Har dard ko chhupa leta hoon main teri yaadon mein.",
      "Tere saath guzare wo pal yaadgaar ban gaye.",
      "Tumhare pyaar ke bina meri duniya sunsaan hai.",
      "Muskurate raho, kyunki teri muskaan meri zindagi hai.",
      "Tere pyaar ka asar ab tak dil par hai.",
      "Sapno ki duniya mein tera intezaar hai.",
      "Tere bina har khushi adhoori lagti hai.",
      "Tumhare jaane ke baad sab kuch veeraan hai.",
      "Dil ke zakmon ko sirf tera pyaar bhar sakta hai.",
      "Teri hansi meri sabse badi daulat hai.",
      "Tere bina har din udaas sa lagta hai.",
      "Meri dhadkanon mein bas tera naam hai.",
    ],
  },
};
